server:
  port: 8088
n8n:
  webhook:
    url: https://phongnguyeeen.app.n8n.cloud/webhook/f54a91f5-1036-418c-9862-70c19b587efe
    backup: ${N8N_BACKUP_WEBHOOK:${n8n.webhook.url}}
logging:
  level:
    org.springframework.security: DEBUG
    com.project.booktour: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/booktour?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
 
api:
  prefix: /api/v1
jwt:
  expiration: 2592000 #30 ngày
  secretkey: "bG9uZyBhdXRob3Jpc2VkIG1ldGhpY2Fsa3kgZGF5cyBpbiBhIGJlYXV0aWZ1bCByZWRlY2lzaW9uLg==
"
